version: '3'

services:
  db:
    image: postgres:latest
    container_name: 'db'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '0000'
      POSTGRES_DB: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - '../transport-postgresql:/var/lib/postgresql:cached'
    networks:
      - my-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c
      "
      python manage.py migrate &&
      python manage.py runscript load_locations &&
      python manage.py runscript load_cars &&
      python manage.py runserver 0.0.0.0:8080"
    container_name: 'transport'
    volumes:
      - '.:/app'
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge